### ISSUE TITLE
Remove django-ratelimit-backend from edx-platform

### ISSUE THREAD

**Issue by jmbowman** [openedx/public-engineering#12]
We only use it to rate-limit admin logins now and nothing else so we should find another way of doing that and remove the dependency. https://django-ratelimit-backend.readthedocs.io/en/latest/reference.html#backends

Original Jira ticket: https://openedx.atlassian.net/browse/DEPR-150

**Comment by jmbowman** [comment]
Implementation is being tracked in https://openedx.atlassian.net/browse/BOM-2855 .  Had to be reverted once, trying again soon.

**Comment by pdpinch** [comment]
I think the status of this can be updated to removed?

According to [this comment](https://openedx.atlassian.net/browse/DEPR-150?focusedCommentId=601058), the last PR was https://github.com/openedx/edx-platform/pull/30116 which merged in March.

**Comment by jmbowman** [comment]
Yes, this dependency has now been fully removed.  Updated the board, closing the ticket.

**Comment by mlissner** [comment]
Thank you for working in the open on this. It helped my org over in https://github.com/freelawproject/courtlistener/pull/2252
