### ISSUE TITLE
[DEPR] bok-choy: remove supporting tooling & archive repo

### ISSUE THREAD

**Issue by feanil** [openedx/public-engineering#13]
## Overview

We propose the removal all remaining bok-choy test suites, all tooling code supporting bok-choy test suites, and the bok-choy test framework itself.

*Target acceptance date:* 2022-02-18

*Earliest possible release without bok-choy:* Nutmeg

## Context

[Bok-Choy](https://github.com/openedx/bok-choy) is a home-grown library allowing acceptance-level tests against Web pages to be written in Python. Over the years, it has been used in a few different places:

* edX’s [end-to-end testing suite for LMS & CMS](https://github.com/edx/edx-e2e-tests)
* edx-platform accessibility tests
* various repositories' acceptance tests suites:
  * edx-platform 
  * edx-ora2
  * edx-notifications
  * ecommerce
  * credentials
  * insights
  * xblock-sdk
  * xblock-drag-and-drop-v2 (very minimal usage)

As we have moved from Django-templated (“legacy”) frontends to React micro-frontends (“MFEs”), bok-choy has fallen out favor, as the framework does not work or make sense to use with MFEs. Even with legacy frontends, we have found their bok-choy test suites to be so slow and flaky that their usefulness has been called into question.

In 2020, [we decided to remove the vast majority of bok-choy acceptance tests from edx-platform](https://github.com/edx/edx-platform/blob/master/docs/decisions/0003-reduce-bokchoy-testing.rst). In 2021, edX decided to [do the same for edx-platform accessibility tests](https://openedx.atlassian.net/browse/BOM-2612).

## Replacement

There is no direct Open edX replacement for bok-choy. Instead, we encourage community members to write acceptance and integration tests using third-party libraries. For example, the new Authentication Micro-Frontend uses [Cypress for end-to-end tests](https://github.com/openedx/cypress-e2e-tests/tree/master/cypress/integration/authenticationMFE).

## Removal steps

* 2U: archive the `edx-e2e-tests` repository.
* For each repository listed under “Context”:
  * Delete all the remaining bok-choy tests.
    * or, if appropriate, refactor end-to-end tests to not use bok-choy instead of deleting them.
  * Remove any settings files, test scripts, or tooling configuration specific to bok-choy.
  * Remove bok-choy from the repository’s requirements list.
* Remove all references to bok-choy and edx-e2e-tests from devstack. Remove the chrome and firefox services.
* Search for “bok-choy” and “bok_choy” in the `openedx` GitHub organization, removing any dangling references to the test library or old test suites.
  * 2U: Do the same for the `edx` GH org.
* Archive the bok-choy repository.

--

Original Jira Issue: https://openedx.atlassian.net/browse/DEPR-174
Communicated to community: https://discuss.openedx.org/t/deprecation-removal-bok-choy-test-suites-framework/6547

**Comment by kdmccormick** [comment]
PR to mark bok-choy as deprecated in its README and ReadTheDocs: https://github.com/openedx/bok-choy/pull/364

**Comment by kdmccormick** [comment]
Big PR of bok-choy cruft removed from edx-platform: https://github.com/openedx/edx-platform/pull/29813

**Comment by feanil** [comment]
@jmbowman what's left to do on this issue?

**Comment by jmbowman** [comment]
Finish moving the e2e tests to Cypress, and look for any remaining usage in other repos that we may have overlooked in our first pass.  I think the e2e switchover is very close to complete, but I'm not sure at the moment what the exact ETA is.

**Comment by kdmccormick** [comment]
@jmbowman just curious, any movement on the e2e switchover, or a relevant ticket we could link to this one?

**Comment by dianakhuang** [comment]
The e2e tests for edx.org have been switched over to using Cypress. I have seen usages of bok choy in credentials and ecommerce, but we can at least start looking into cleaning out some of edx-platform.

**Comment by robrap** [comment]
Here are some github searches to see some current uses:

Search code:
* https://github.com/search?q=org%3Aopenedx+bokchoy&type=code
* https://github.com/search?q=org%3Aopenedx+bok_choy&type=code

Search repo files, like:
* https://github.com/openedx/edx-platform/find/master (search for "bokchoy")

**Comment by kdmccormick** [comment]
PyPI is now updated:
![image](https://user-images.githubusercontent.com/3628148/233101478-c9e75e8b-1d17-47cd-89fe-c6e126a3f1f7.png)

**Comment by robrap** [comment]
@kdmccormick: I'm not sure what the refactor should be, but the bok_choy.yml file is used in the following github workflows:
* https://github.com/openedx/edx-platform/blob/2edbdcf7f48eddeff9fc6f1967e3f11be8c8e390/.github/workflows/migrations-check-mysql8.yml#L71-L80
* https://github.com/openedx/edx-platform/blob/2edbdcf7f48eddeff9fc6f1967e3f11be8c8e390/.github/workflows/migrations-check.yml#L84
* https://github.com/openedx/edx-platform/blob/90f4f6543deb39517b75b61b15ba8ff557a873dc/.github/workflows/static-assets-check.yml#L67-L68

**Comment by kdmccormick** [comment]
@robrap as it turns out, that was actually what led me back to this DEPR ticket today 😄 

I'm [currently experimenting](https://github.com/openedx/edx-platform/pull/32100) with replacing those with the [minimal.yml](https://github.com/openedx/edx-platform/blob/master/lms/envs/minimal.yml) files that @feanil recently introduced. What we really need is a broader configuration cleanup, but in the short term I'm hoping minimal.yml will do that trick.

**Comment by feanil** [comment]
@dianakhuang @kdmccormick I'm gonna put this on the backlog for the new Aximprovements team.  I'm gonna continue to follow @kdmccormick 's lead and create tickets to let people know that bok-choy has been deprecated but plan on archiving the repo before all services have moved off of bok-choy.  They can continue to use the old version but we should not make new updates.  Once the Aximprovements team has reviewed and created tickets for all repos that still use bok-choy.  I can communicate to the relevant owners to let them know the situation and leave it to them to prioritize. 

I've created https://github.com/openedx/axim-engineering/issues/874 to track the exact work the Aximprovements team will be doing.

**Comment by salman2013** [comment]
PR for bok-choy settings removal from edx-platform https://github.com/openedx/edx-platform/pull/33350

**Comment by dianakhuang** [comment]
@feanil What's the current status of this? Can it be moved into 'removed'?

**Comment by feanil** [comment]
@salman2013 I've archived the bok-choy and edx-custom-a11y-rules repos.  There are still a bunch of mentions of bokchoy in the platform, can you review them and open PRs for any that should be cleaned up?  https://github.com/search?q=org%3Aopenedx%20bokchoy&type=code  Once that's done, I think we can close this.

**Comment by kdmccormick** [comment]
"bokchoy": https://github.com/search?q=org%3Aopenedx+%22bokchoy%22&type=code

"bok choy": https://github.com/search?q=org%3Aopenedx+%22bok+choy%22&type=code

"bok-choy": https://github.com/search?q=org%3Aopenedx+%22bok-choy%22&type=code

"bok_choy": https://github.com/search?q=org%3Aopenedx+%22bok_choy%22&type=code

**Comment by feanil** [comment]
@salman2013 can you take a look at the searches that Kyle provided and clean those up as well?

**Comment by salman2013** [comment]
@kdmccormick @feanil There is a PRs to remove remaining bok-choy references. 

- https://github.com/openedx/edx-platform/pull/34216
- https://github.com/openedx/configuration/pull/7101
- https://github.com/openedx/openedx-backstage/pull/34
- https://github.com/openedx/docs.openedx.org/pull/466
- https://github.com/openedx/FeedbackXBlock/pull/59
- https://github.com/openedx/registrar/pull/594

**Comment by salman2013** [comment]
@kdmccormick These [search result](https://github.com/search?q=org%3Aopenedx+%22bok-choy%22&type=code) are found in release notes so I leave them intentionally. Could you please check if this should also be removed then i can do that.

**Comment by kdmccormick** [comment]
Thanks @salman2013 . I'll take a look at the edx-platform, feedbackblock, and registrar PRs.

> These [search result](https://github.com/search?q=org%3Aopenedx+%22bok-choy%22&type=code) are found in release notes so I leave them intentionally. Could you please check if this should also be removed then i can do that.

Leaving those there is the right thing to do 👍🏻

**Comment by feanil** [comment]
I had a question on the FeedbackXBlock Pr but everything else is merged.

**Comment by robrap** [comment]
Here is a 2U specific search, but one that other orgs can use if they want to remove their own bokchoy references. It uses 4 versions of the term found above:
https://github.com/search?q=org%3Aedx+%28%22bok-choy%22+OR+%22bok+choy%22+OR+%22bok_choy%22+OR+%22bokchoy%22%29++NOT+is%3Aarchived&type=code

**Comment by timmc-edx** [comment]
Or if you want to be really thorough, GitHub search now supports regular expressions like `/bok.?choy/` :-D
