### ISSUE TITLE
[Deprecation Warning]: The 'warn' method is deprecated, use 'warning' instead

### ISSUE THREAD

**Issue by UsamaSadiq** [openedx/public-engineering#149]
### Description
- `Python test warnings Suppression` process has been started to squash/fix the existing `pytest warnings` from `edx-platform`.
- The details to handle the warnings and current warnings report can be found in the [document](https://openedx.atlassian.net/wiki/spaces/AC/pages/3426386029/How+to+fix+edx-platform+Unit+Test+Warnings)

**Comment by UsamaSadiq** [comment]
label: help wanted

**Comment by UsamaSadiq** [comment]
label: maintenance

**Comment by Younggregs** [comment]
Hello @UsamaSadiq is this issue still open?

**Comment by UsamaSadiq** [comment]
@Younggregs the deprecation warnings occurring due to third party packages are still open. 
You can see the latest warnings report from edx-platform github actions summary tab and see which warnings are still occurring.

**Comment by lewisemm** [comment]
assign me

**Comment by UsamaSadiq** [comment]
@lewisemm Thanks for the contribution. I'll review your PR once the tests pass on it.
