### ISSUE TITLE
[DEPR] xblock.fragment and direct id_generator parameters in xblock.runtime.Runtime

### ISSUE THREAD

**Issue by jmbowman** [openedx/public-engineering#15]
### Removal

**Removing:** The `xblock.fragment` module and deprecated `id_generator` method parameters in `xblock.runtime`.

**Includes**:

* `xblock.fragment` (removed completely)
* `xblock.runtime.Runtime._aside_from_xml` (just the id_generator argument)
* `xblock.runtime.Runtime._usage_id_from_node` (just the id_generator argument)
* `xblock.runtime.Runtime.add_node_as_child` (just the id_generator) argument)
* `xblock.runtime.Runtime.parse_xml_string` (just the id_generator) argument)
* `xblock.runtime.Runtime.parse_xml_file` (just the id_generator argument)

### Replacement

Replaced with: the `web-fragments` package, and the `id_generator` argument to `xblock.runtime.Runtime.__init__()`

### Target Dates

Accepted (deadline for comments before acceptance): 2020-01-13

### Removed: 2020-01-24

First named release without it: Juniper release

Additional Context

The `id_generator` arguments have been explicitly deprecated for more than 5 years.  `xblock.fragment` has been explicitly deprecated for almost 3 years.  We're just following through and finally removing them.

Original ticket: https://openedx.atlassian.net/browse/DEPR-59

**Comment by jmbowman** [comment]
A proposed PR to make the relevant changes in the XBlock repository once all related code has been updated exists at https://github.com/edx/XBlock/pull/440 .  The updating of said related code is just waiting on resources to get it done.

**Comment by kdmccormick** [comment]
Latest update was 2021-07-06 from @dianakhuang : 
> This removal work is just waiting for resources to do it. If the DEPR working group gets a chance, we will try to do it ourselves.

**Comment by jmbowman** [comment]
I've assigned this to the Arbi-BOM squad, they should be able to start work on it relatively soon.

**Comment by UsamaSadiq** [comment]
I'll start working on this issue. @jmbowman please assign this issue to me as I don't have permission to change the assignee.
