### ISSUE TITLE
[DEPR]: Dropping support of fields in refresh_course_metadata

### ISSUE THREAD

**Issue by dianakhuang** [openedx/public-engineering#160]
### Proposal Date

25 July 2022

### Ticket Acceptance Date

8 August 2022

### Technology Removal Date

8 August 2022

### First Open edX Named Release Without This Functionality

Olive

### Rationale

We are removing these fields from the sync job because we believe that course-discovery is and should be the source of truth for this data going forward for installations of Open edX that use course-discovery and not edx-platform.

### Removal

We will be dropping support for these fields in refresh_course_metadata: 
```
card_image_url
short_description_override
video
mobile_available
```

The code to sync this data:
https://github.com/openedx/course-discovery/blob/master/course_discovery/apps/course_metadata/data_loaders/api.py#L252-L257
https://github.com/openedx/course-discovery/blob/master/course_discovery/apps/course_metadata/data_loaders/api.py#L270-L273

### Replacement

Since this data was merely being synced from edx-platform to course-discovery, we will only be considering the data in course-discovery to be the source of truth.

**Comment by rgraber** [comment]
It turns out these fields are still used in setups that don't have publisher, so I don't think we can actually deprecate.

**Comment by dianakhuang** [comment]
Since these fields are still used in some cases, we are going to abandon this DEPR.
