### ISSUE TITLE
Explore option to better track status of Open PRs

### ISSUE THREAD

**Issue by feanil** [openedx/public-engineering#172]
Currently we are using labels on PR as a way of tracking basic status like, needs-product-review, needs-tests-run, waiting-on-author.  This is imperfect and makes it hard for the team triaging and routing PRs to keep track of what they have already reviewed.  This ticket is to explore what options we have to better track the status of PRs including:

1. what is the current state of this PR
2. who is currently in the hot seat
3. how long has it been in the current state

**Comment by feanil** [comment]
@e0d do you think there is more to do with this after the conversations we had yesterday? I think using the [Contributions](https://github.com/orgs/openedx/projects/19) board and adding the relevant fields solves the issues you brought up in this ticket.

**Comment by e0d** [comment]
No, I think we've done the work.
