### ISSUE TITLE
outcome-surveys - Installed by default but still in the edx org, looks to be learning related.

### ISSUE THREAD

**Issue by feanil** [openedx/public-engineering#177]

**Comment by feanil** [comment]
FYI https://github.com/openedx/public-engineering/issues/178 is in the same boat if it makes more sense to look into both at the same time.

**Comment by nedbat** [comment]
I'll investigate both.

**Comment by nedbat** [comment]
I sent an email to Markhors raising the issue.

**Comment by nedbat** [comment]
Nathan Robertson says:
> We've pinned this for the sprint starting August 2nd. Should be done shortly after that.

**Comment by feanil** [comment]
This was removed in https://github.com/openedx/edx-platform/pull/32796 so closing this tracking ticket.
