### ISSUE TITLE
learner-pathway-progress - Installed by default but still in the edx org, looks to be learning related.

### ISSUE THREAD

**Issue by feanil** [openedx/public-engineering#178]

**Comment by nedbat** [comment]
I sent an email to Markhors raising the issue.

**Comment by nedbat** [comment]
Nathan Robertson says:
> We've pinned this for the sprint starting August 2nd. Should be done shortly after that.

**Comment by feanil** [comment]
Looks like this was removed from the default bundle.in in https://github.com/openedx/edx-platform/pull/32796

Closing this tracking ticket.
