### ISSUE TITLE
Audit READMEs of repos migrated from edx-solutions to openedx

### ISSUE THREAD

**Issue by kdmccormick** [openedx/public-engineering#186]
## Context

Repos such as [xblock-drag-and-drop-v2](https://github.com/openedx/xblock-drag-and-drop-v2), which have been moved in from the edx-solutions organizations, have statements in their READMEs such as "this repository will be moved to the edx organization in April 2021" or "this repository will be archived in April 2021".

## Acceptance Criteria

For each [repository migrated in from edx-solutions](https://docs.google.com/spreadsheets/d/1vxuwG9z7-iHXuIFUVrxR8Giq8kvDvMrLJE4FrrehJnc/edit#gid=0), check out its README.
  * If it says it's moving to the edx organization, remove that notice.
  * If it says it's being archived, then:
    * archive it (if that's the obvious course of action),
    * remove the notice (if it's clear we still care about it),
    * create a DEPR ticket for it (if it's clear we want to archive it, but need to get community agreement first), or
    * create a backlog issue to follow up on the repo (if it's not clear what to do).

**Comment by feanil** [comment]
I looked through all the repos listed and it looked like only one still had this issue: https://github.com/openedx/xblock-google-drive/pull/62

**Comment by feanil** [comment]
The above PR has now been merged so this should be all set.
