### ISSUE TITLE
[DEPR]: Complete removal of EdxRestApiClient

### ISSUE THREAD

**Issue by robrap** [openedx/public-engineering#189]
### Proposal Date

11 April 2023

### Target Ticket Acceptance Date

11 April 2023

### Earliest Open edX Named Release Without This Functionality

Q - 2023-10

### Rationale

Note that this is not a new proposal, but is a ticket to track completion of the original DEPR documented here: https://github.com/openedx/public-engineering/issues/37.

This ticket is to clean-up some small remaining usages, and ultimately to remove the deprecated `EdxRestApiClient` so the code no longer lives in the platform.

### Removal

Here is a general search for uses of `EdxRestApiClient`: https://github.com/search?q=org%3Aopenedx%20EdxRestApiClient&type=code

- [x] Here is usage in edx-platform: https://github.com/openedx/edx-platform/blob/d622db59b7bfe2e4c11fc11b7cb2d475cfda551b/openedx/core/djangoapps/commerce/utils.py#L56
- [x] Here is a comment that simply should no longer reference `EdxRestApiClient`: https://github.com/openedx/edx-analytics-data-api/blob/6916f071301c57457cad668ac1c33ae702b061fa/analyticsdataserver/settings/base.py#L325
- [ ] It's unclear if this is still an active use, but it definitely needs to be addressed: https://github.com/openedx/credentials/blob/b6090f97097aee61e927f375995a10582adc0731/credentials/apps/catalog/utils.py#L37
- [x] Tests that should be removed. Do they need to be replaced? See https://github.com/openedx/edx-platform/blob/d622db59b7bfe2e4c11fc11b7cb2d475cfda551b/lms/djangoapps/commerce/tests/__init__.py#L28.
- [ ] More tests using the client. Are these credentials e2e tests still in use? See https://github.com/openedx/credentials/blob/b6090f97097aee61e927f375995a10582adc0731/acceptance_tests/e2e/mixins.py#L38.
- [x] The final change should be removal of the actual class in a breaking change. We should also remove the ``slumber`` library, since we will no longer need this outdated library. See https://github.com/openedx/edx-rest-api-client/blob/8eb8837c2d5e94ef2cc809124ed371ef12509f50/edx_rest_api_client/client.py#L288
  - [x] Includes tests for this class: https://github.com/openedx/edx-rest-api-client/blob/8eb8837c2d5e94ef2cc809124ed371ef12509f50/edx_rest_api_client/tests/test_client.py#L37
- [X] There is a separate ticket for follow-up on an ADR detailed in https://github.com/openedx/edx-rest-api-client/issues/277. Marking this closed to not block closing this DEPR, although the issue has not yet been addressed.
- [ ] The newly introduced `DeprecatedEdxRestApiClient` in edx-platform will need to be removed, in addition to ``slumber``. This requires fixing the past bug found during the first attempt. See https://github.com/openedx/public-engineering/issues/189#issuecomment-1839078231 for details. (This may die with ecommerce code in edx-platform. This should probably just get its own edx-platform ticket rather than trying to complete as part of this DEPR.)

### Replacement

See original DEPR for details: https://github.com/openedx/public-engineering/issues/37

**Comment by kdmccormick** [comment]
I support this deprecation! 😉

**Comment by idegtiarov** [comment]
me too )))

**Comment by robrap** [comment]
Note that I have questions about some of the replacement work from the original DEPR ticket, but I have created the following ticket to address that: https://github.com/openedx/edx-rest-api-client/issues/277

**Comment by Yagnesh1998** [comment]
assign me

**Comment by Yagnesh1998** [comment]
think some parts will already be covered in [PR 33603](https://github.com/openedx/edx-platform/pull/33603) and [PR303](https://github.com/openedx/edx-rest-api-client/pull/303)

**Comment by robrap** [comment]
@dianakhuang @feanil: At some point we had discussed removing EdxRestApiClient from the library, and updating edx-platform's lone usage (that snuck back in) by making a local copy, renamed to DeprecatedEdxRestApiClient, so hopefully no ohter usages would crop up.

@Yagnesh1998 was working on that, and it struck me that:
1. This DEPR won't be closed until we actually got rid of any new `DeprecatedEdxRestApiClient`, especially because this requires slumber library that we wish to retire, and
2. Since we need to get rid of it anyway, is it possible to simply introduce a fix to use the new client (or `requests`) without ever introducing `DeprecatedEdxRestApiClient`?

I've asked @Yagnesh1998 to look into that based on PRs from the original DEPR work.

**Comment by robrap** [comment]
@dianakhuang:
1. Are the checkboxes on this ticket out-of-date?
2. Can we get https://github.com/openedx/public-engineering/issues/218#issuecomment-2310312217 over the line?
3. Should removal of `DeprecatedEdxRestApiClient` from edx-platform get its own edx-platform issue, whether it is a DEPR or not?

Basically, I'm wondering how to get these related DEPR tickets closed.

**Comment by dianakhuang** [comment]
1. I think they probably are, but I haven't had time to really review them.
2. Yup, I would like to do that asap.
3. I think maybe we should create one when we get a chance. Maybe we can discuss during the DEPR meeting. I think it will depend on when ecommerce actually gets killed. It feels like it's been on the verge for the last few years.

**Comment by dianakhuang** [comment]
The ecommerce code will be removed within the next year anyway from edx-platform and the DEPR work for cleaning up DeprecatedRestApiClient will go with it, so we aren't making a separate ticket.
