### ISSUE TITLE
ReadTheDocs will require .readthedocs.yml files in September

### ISSUE THREAD

**Issue by nedbat** [openedx/public-engineering#196]
ReadTheDocs is going to require .readthedocs.yml files in September: https://blog.readthedocs.com/migrate-configuration-v2/

We've written a ticket for the 2U Arbi-BOM team to start the planning work: https://github.com/edx/edx-arch-experiments/issues/316

**Comment by irtazaakram** [comment]
All repos have been updated to v2 by Arbi-BOM https://github.com/edx/edx-arch-experiments/issues/418
