### ISSUE TITLE
[Course-discovery]: Django 4.2 Upgrade

### ISSUE THREAD

**Issue by UsamaSadiq** [openedx/public-engineering#207]
## Description
Under the effort of [Django 4.2 Upgrade](https://github.com/openedx/public-engineering/issues/199), complete all of the following steps to complete the upgrade. 

- [ ] Update tox & Github action workflow using modernisers to add support for `Django 4.2`
- [ ] Remove any versions of Django earlier than 4.2 from `tox.ini`, and `GitHub Actions` workflows.
- [ ] Remove any versions of Python earlier than 3.8 from `tox.ini`, and `GitHub Actions` workflows.
- [ ] Override the pinned `Django<3.2` constraint in the common_constraints to `Django<4.0` to override the global Django constraint.
- [ ] Add a local constraint of `Django<5.0` and run `make upgrade` to update all dependencies for `Django 4.2`.
- [ ] Run and verify all tests are passing in the CI for both `Django 4.2`.
- [ ] Run available code-mods to fix the failing tests. 
- [ ] Update the repo support field in the [IDA Upgrade Sheet](https://openedx.atlassian.net/wiki/spaces/AC/pages/3815637011/Django+4.2+Upgrade+List+of+IDAs).

**Comment by gsueros** [comment]
PR in progress for Django 4.2 upgrade https://github.com/openedx/course-discovery/pull/4088
