### ISSUE TITLE
[DEPR]: Remove OLX `problemset` and `videosequence` as aliases to `sequential`

### ISSUE THREAD

**Issue by pdpinch** [openedx/public-engineering#21]
### Proposal Date

2021-03-20

### Ticket Acceptance Date

2021-04-19

### Technology Removal Date

2021-04-20

### First Open edX Named Release Without This Functionality

Nutmeg

### Rationale

`problemset` and `videosequence` are old-but-not-entirely-unused aliases to the `sequential` (in Studio-speak, "Subsection")  block type.

We’ll be deprecating use of the `problemset` and `videosequence` tags. While we felt that there may be merit to the idea of more specific types of Sequences, the current implementation of it only adds complexity and does not surface much benefit to authors or any benefit to learners.

## Usage

Currently there are only a ~hundred or so usages of these aliases on edx.org, primarily amongst the oldest courses that were hand-authored in OLX. Studio does not support these aliases.

It seems that Block Transformers (or some other piece of code) gets confused by these block types, seemingly treating the children of `problemset` as children of the parent chapter (i.e. Section). As an example, the “Problem: …” verticals (i.e. Units) shown below should actually be nested under a `problemset`, instead of being direct children of the Week 1 chapter:

### Removal

The remaining code to handle `problemset` and `videosequence` should be removed by https://github.com/openedx/edx-platform/pull/29905

### Replacement

Any remaining `problemset` and `videosequence` can be converted to `sequential`

**Comment by pdpinch** [comment]
@ormsbee it looks like the remaining PR https://github.com/openedx/edx-platform/pull/29905 was merged a couple of months ago and is included in nutmeg. Can the status be updated to "removed" ?

**Comment by ormsbee** [comment]
Yup!
