### ISSUE TITLE
[license-manager]: Django 4.2 Upgrade

### ISSUE THREAD

**Issue by UsamaSadiq** [openedx/public-engineering#210]
## Description
Under the effort of [Django 4.2 Upgrade](https://github.com/openedx/public-engineering/issues/199), complete all of the following steps to complete the upgrade. 

- [x] Update tox & Github action workflow using modernisers to add support for `Django 4.2`
- [x] Remove any versions of Python earlier than 3.8 from `tox.ini`, and `GitHub Actions` workflows.
- [x] Update the pinned `Django` version in the requirements to `Django==4.2`
- [x] Run `make upgrade` to update all dependencies for `Django 4.2`.
- [x] Run and verify all tests are passing in the CI for both `Django 4.2` and `Django 3.2` to contain backward compatibility.
- [ ] Run available code-mods to fix the failing tests. 
- [ ] Add conditional checks wherever needed to still have support for `Django 3.2`. 
- [ ] Update the repo support field in the [IDA Upgrade Sheet](https://openedx.atlassian.net/wiki/spaces/AC/pages/3815637011/Django+4.2+Upgrade+List+of+IDAs).

**Comment by Younggregs** [comment]
Hello @UsamaSadiq i will like to take one of the issues, can I proceed?

**Comment by UsamaSadiq** [comment]
> Hello @UsamaSadiq i will like to take one of the issues, can I proceed?

Hi @Younggregs most of these issues related to Django 4.2 have already been completed. 
The status of all these issues will be updated by next week so if you could wait till next week, you'll be sure on which issues are left to be picked.

**Comment by Younggregs** [comment]
Alright, @UsamaSadiq thank you for the feedback, I'll wait then. Meanwhile are there any open issues you can recommend to me, please? I'll like to try something out before then, its my first time contributing

**Comment by Younggregs** [comment]
Hello @UsamaSadiq has these been completed? it's been over some weeks now
