### ISSUE TITLE
[demographics]: Django 4.2 Upgrade

### ISSUE THREAD

**Issue by awais786** [openedx/public-engineering#211]
Under the effort of [Django4.2 upgrade](https://github.com/openedx/public-engineering/issues/199) complete all of the following steps to complete the upgrade.

- [x]  Update tox & Github action workflow using modernisers to add support for Django 4.2
- [x]  Remove any versions of Python earlier than 3.8 from tox.ini, and GitHub Actions workflows.
- [ ]  Update the pinned Django version in the requirements to Django==4.2
- [ ]  Run make upgrade to update all dependencies for Django 4.2.
- [ ]  Run and verify all tests are passing in the CI for both Django 4.2 and Django 3.2 to contain backward compatibility.
- [ ]  Run available code-mods to fix the failing tests.
- [ ]  Add conditional checks wherever needed to still have support for Django 3.2.
- [ ]  Update the repo support field in the [IDA Upgrade Sheet](https://openedx.atlassian.net/wiki/spaces/AC/pages/3815637011/Django+4.2+Upgrade+List+of+IDAs).

**Comment by awais786** [comment]
Django42 support PR merged and deployed. Now Its a blocker due to mysql8.

**Comment by Younggregs** [comment]
Hello @awais786 I will like to pick one of the open issues, can I proceed?

**Comment by awais786** [comment]
@Younggregs its already done. But fail to miss the issue status. Django42 upgrade almost done.
But lots of other issues available. Thanks for your offer.
