### ISSUE TITLE
[DEPR]: Removal of Deprecated and unused feature flags from Mobile-Config Repo

### ISSUE THREAD

**Issue by omerhabib26** [openedx/public-engineering#213]
### Proposal Date

2023-08-02

### Target Ticket Acceptance Date

2023-08-16

### Earliest edX Named Release Without This Functionality

**These changes aren’t tied to an Open edX release and are only dependent on Mobile releases as mentioned below:**
Android Release 4.0.2
iOS Release 3.2.5

### Rationale

As a mobile code improvement, we need to remove the deprecated/unused feature flags from Mobile Config as decided in [LEARNER-8703](https://2u-internal.atlassian.net/browse/LEARNER-8703)
 

### Removal

The following flags will no longer be available for development.

1. TAB_LAYOUTS_ENABLED
2. SECRET flag under BRANCH {Dict}
3. ZERO_RATING
4. SOCIAL_SHARING
5. IAP_ENABLED
6. API_KEY flag under YOUTUBE_PLAYER {Dict}

### Replacement

The detailed description can be found on the relative Wikis on [Open edX confluence](https://openedx.atlassian.net/wiki/spaces/LEARNER/pages/48792067/App+Configuration+Flags) and [2U confluence](https://2u-internal.atlassian.net/wiki/spaces/LEARNER/pages/7150066/App+Configuration+Flags).

### Additional Info

After a detailed spike on both platforms (Android & iOS) in [LEARNER-8703](https://2u-internal.atlassian.net/browse/LEARNER-8703), we decided to remove the mentioned flags from [Android](https://2u-internal.atlassian.net/browse/LEARNER-9037) & [iOS](https://2u-internal.atlassian.net/browse/LEARNER-9432) and will be rolled out in the coming releases.

**Comment by miankhalid** [comment]
@omerhabib26 It'd be nice if you can mention that this change isn't tied to an Open edX release and would depend on the Android App's Release version as well as iOS's under the section:

> Earliest Open edX Named Release Without This Functionality

Also under Additional Info, I think it would make sense to have the ticket link again.
