### ISSUE TITLE
Create a checklist for removing server side rendered templates and moving them into an MFE

### ISSUE THREAD

**Issue by dianakhuang** [openedx/public-engineering#219]
We have run into some standard issues for moving legacy frontends into MFEs when we try to remove the old legacy frontend code. We would like to have a checklist so that we can avoid common pitfalls.

**Comment by kdmccormick** [comment]
I've added this to https://github.com/openedx/wg-frontend/issues/156 for tracking

**Comment by kdmccormick** [comment]
I believe that https://github.com/openedx/wg-frontend/issues/156 and its children tickets capture this well enough
