### ISSUE TITLE
[DEPR]: openedxstats and openedx-census

### ISSUE THREAD

**Issue by nedbat** [openedx/public-engineering#222]
### Proposal Date

2023-07-28

### Target Ticket Acceptance Date

2023-09-01

### Earliest Open edX Named Release Without This Functionality

N/A: this is not part of a release

### Rationale

These tools were written to scrape the web for Open edX sites, but they have not been used in perhaps two years?  The only activity has been organization-wide upgrades to tooling and dependencies, which is wasted work.

### Removal

https://github.com/openedx/openedxstats
https://github.com/openedx/openedx-census

### Replacement

We have no replacement.

**Comment by feanil** [comment]
The app has been shutdown and both repos have been archived and moved to openedx-unsupported.
