### ISSUE TITLE
Add renovate.json  config in missing repositories

### ISSUE THREAD

**Issue by feanil** [openedx/public-engineering#223]
Add renovate.json config file in missing repositories. 
Ensure all repositories which have package.json files also have renovate.json config files.

When we add this file, we should add it to the `.github` folder instead of the top level location.
We should also move all the other renovate.json files to the `.github`

Links:
- https://docs.renovatebot.com/configuration-options/
- https://docs.openedx.org/en/latest/developers/how-tos/enable-javascript-upgrade-automation.html

**Comment by salman2013** [comment]
@feanil There is one [PR](https://github.com/openedx/frontend-enterprise/pull/374) left under this ticket after that this is good to close.

**Comment by feanil** [comment]
Ok, last PR has been merged, so we can call this done!
