### ISSUE TITLE
[DEPR]: django-splash

### ISSUE THREAD

**Issue by ormsbee** [openedx/public-engineering#224]
### Proposal Date

2024-01-25

### Target Ticket Acceptance Date

2024-02-09

### Earliest Open edX Named Release Without This Functionality

Redwood - 2024-04

### Rationale

The [django-splash](https://github.com/openedx/django-splash) repo was created 11 years ago to let the LMS redirect users to a splash screen when a user comes to the site for the first time. It works by looking for a configurable cookie value and redirecting from the middleware.

This feature was never documented, has some edx.org hardcoded defaults, and is not compatible with MFEs.

### Removal

* https://github.com/openedx/django-splash
* https://github.com/openedx/edx-platform/blob/bca34c0993aa7004b86cbf318ea55fd3a0ca5d95/lms/envs/common.py#L3134

### Replacement

There is no planned replacement for this.

**Comment by ormsbee** [comment]
Communicated here: https://discuss.openedx.org/t/deprecation-removal-django-splash/12179

**Comment by feanil** [comment]
The code has been removed from edx-platform and the repository has been archived.  Waiting a little bit to make sure there are no regressions before closing this.
