### ISSUE TITLE
[DEPR]: edx-transifex-bot

### ISSUE THREAD

**Issue by robrap** [openedx/public-engineering#225]
### Proposal Date

2024-01-31

### Target Ticket Acceptance Date

2024-01-31

### Earliest Open edX Named Release Without This Functionality

S - 2024-10

### Rationale

See [OEP-58: Translations Management](https://open-edx-proposals.readthedocs.io/en/latest/architectural-decisions/oep-0058-arch-translations-management.html)

### Removal

See [OEP-58: Translations Management](https://open-edx-proposals.readthedocs.io/en/latest/architectural-decisions/oep-0058-arch-translations-management.html)

See [github search for removing Transifex calls](https://github.com/pulls?q=OEP-58+FC-0012+is%3Aopen+is%3Apr+draft%3Atrue+%22remove+Transifex+calls%22+)

### Replacement

See [OEP-58: Translations Management](https://open-edx-proposals.readthedocs.io/en/latest/architectural-decisions/oep-0058-arch-translations-management.html)

### Additional Info

Also see an [OEP-58 overview page in the wiki](https://openedx.atlassian.net/wiki/spaces/AC/pages/3800203265/OEP-58+Overview).

**Comment by robrap** [comment]
Note: This ticket was accepted as part of the OEP, and is being added here as a redundant form of communication about this work.

**Comment by dianakhuang** [comment]
We are going to remove the transifex bot from the translations and openedx groups and see what breaks.

**Comment by dianakhuang** [comment]
This user still exists and has permissions but only the openedx-translations repo (which makes sense).

It was also renamed to the openedx-transifex-bot.
