### ISSUE TITLE
[DEPR] Deprecate 'entrance exam' feature.

### ISSUE THREAD

**Issue by feanil** [openedx/public-engineering#23]
"Entrance Exams date from 2015, and have not been used by edX. They have only been used rarely (if at all?) by partners. They were excluded from the MFE. Therefore we have decided to deprecate them.

https://discuss.openedx.org/t/deprecation-removal-of-entrance-exam-feature/5642

*Target Dates:*

* Accepted: September 3 2021
* Removed: *\[UPDATED]* removal date is determined by [https://openedx.atlassian.net/browse/DEPR-109|https://openedx.atlassian.net/browse/DEPR-109|smart-link] 

*Open edX Release:*

* Maple

*Removal:* basic summary of feature to be removed:

* Courses can have an Entrance Exam. An entrance exam must be passed before the user can see any other content.
** If a learner has not yet passed an entrance exam they should be redirected to it
** A message should appear above the exam sequence nav indicating the state of the exam
*** 'To access course materials, you must score \{required_score}% or higher on this exam. Your current score is \{current_score}%.'
*** 'Your score is \{current_score}%. You have passed the entrance exam.'
*** [https://github.com/edx/edx-platform/blob/b33798a450ce80d0dec3c108d40a8095274ef748/lms/templates/courseware/courseware.html#L199-L232|https://github.com/edx/edx-platform/blob/b33798a450ce80d0dec3c108d40a8095274ef748/lms/templates/courseware/courseware.html#L199-L232]   
** All course page tabs navigation should be hidden and replaced with a single “Entrance Exam” tab.
** Spy on ajax requests containing xmodule_handler/problem_check and if their responses contain data.entrance_exam_passed. Then update the message above appropriately 

*Replacement:*

* Nothing will replace the feature."

### Additional Info
https://openedx.atlassian.net/browse/DEPR-163

**Comment by jmyatt** [comment]
I propose changing the status of this DEPR to Abandoned/Rejected and closing this issue. This deprecation was a blocker to https://github.com/openedx/public-engineering/issues/53 until Entrance Exam support was built into frontend-app-learning which is now [done](https://github.com/openedx/frontend-app-learning/commit/57c3f3080eaa173be5a68bffc1269997877e336f).

**Comment by feanil** [comment]
Closing the issue as Abandoned/Rejected.
