### ISSUE TITLE
Update all Released JS Libraries to support Node 20

### ISSUE THREAD

**Issue by feanil** [openedx/public-engineering#232]
```[tasklist]
### Tasks
- [ ] https://github.com/openedx/frontend-lib-special-exams/issues/151
```

**Comment by brian-smith-tcril** [comment]
I've updated https://github.com/openedx/public-engineering/issues/267 to include a tasklist for libraries/other, as I've found it easier to check one place for all the issues/PRs.

I'm going to close this in favor of tracking those over there, if you'd rather I move that tasklist over here I can reopen this and do that instead.

**Comment by feanil** [comment]
That seems fine, yea I think in the future we could even try multiple task lists on just one parent ticket which might further simplify things.
