### ISSUE TITLE
Update all Python Libraries to Test on Python 3.11 and 3.12

### ISSUE THREAD

**Issue by feanil** [openedx/public-engineering#233]
```[tasklist]
### Tasks
- [ ] https://github.com/openedx/public-engineering/issues/236
```

**Comment by awais786** [comment]
@feanil Here is the list of all openedx [packages](https://docs.google.com/spreadsheets/d/19-BzpcX3XvqlazHcLhn1ZifBMVNund15EwY3QQM390M/edit#gid=0).

Running multiple python versions for testing and fix warnings/code changes. All individual sub-tickets require here ?

**Comment by awais786** [comment]
I tried to run `edx-platform` against all python versions 3.9, 3.10 and 3.11. I am doing this using `github hosted runner`.   

Python 3.9 = https://github.com/openedx/edx-platform/pull/34196
python 3.10 = https://github.com/openedx/edx-platform/pull/34201
python 3.11 = https://github.com/openedx/edx-platform/pull/34202

**Comment by UsamaSadiq** [comment]
FYI @feanil 
These upgrade PRs have been created for the community using automated `bulk repo update` job & modernizer scripts. I've linked them all to this issue to keep track of all the PRs. 

For following repos, the bulk job failed to create PRs after making the changes [may have been permissions issues] so these repos will need to be either updated through the `bulk repo update job` in `openedx/.github` repo or community will need to create PRs manually in these repos. 
```
- codejail-includes
- pinax-announcements
- bok-choy
- olxcleaner
- blockstore
- codejail
```

**Comment by awais786** [comment]
https://github.com/openedx/django-pyfs/pull/181

**Comment by awais786** [comment]
https://github.com/openedx/edx-search/pull/145

**Comment by feanil** [comment]
All libraries that are critical to the Open edX release have been updated and for the rest, we'll do them as people have capacity/need given our lower maintenance capacity.
