### ISSUE TITLE
[DEPR]: Replace PDF course certificate view code in edx-platform

### ISSUE THREAD

**Issue by feanil** [openedx/public-engineering#27]
### Proposal Date

06 July 2021

### Ticket Acceptance Date

6 July 2021

### Technology Removal Date

TBD

### First Open edX Named Release Without This Functionality

TBD

### Rationale

PDF course certificates will no longer be viewable.

### Removal

edX-platform currently has code for both PDF and web (or HTML) course certificates. Over time, much of the PDF certificate code has been deprecated or disabled in favor of web certificates. In particular, edX-platform has not supported the generation of PDF course certificates for some time. 

A prior DEPR ticket (https://openedx.atlassian.net/browse/DEPR-155) covers the removal of the code in edx-platform that generates PDF certificates.

This DEPR ticket covers the removal of the code in edx-platform that allows PDF certificates to be viewed. PDF course certificates will no longer be viewable.

### Replacement

Web (HTML) course certificates will continue to be supported. All course runs that use course certificates should be configured to use web certificates.

To configure web certificates, or switch a course run from using PDF certificates to web certificates, follow the documentation to Enable Course Certificates and Set Up Certificates in Studio:

    Enable Course Certificates - https://edx.readthedocs.io/projects/edx-installing-configuring-and-running/en/latest/configuration/enable_certificates.html

    Set Up Certificates in Studio - https://edx.readthedocs.io/projects/open-edx-building-and-running-a-course/en/latest/set_up_course/studio_add_course_information/studio_creating_certificates.html

### Additional Info

Original Jira Issue: https://openedx.atlassian.net/browse/DEPR-157

**Comment by mariajgrimaldi** [comment]
Hi @feanil :smile:, I'm wondering what's the state of this issue? I'm asking because I'm having some problems testing PDF certificates in nutmeg, [here's](https://github.com/openedx/build-test-release-wg/issues/167) the issue I opened in the BTR wg repo.

**Comment by feanil** [comment]
@mariajgrimaldi so, the code to generate PDF certs is long dead.  How did you generate the Cert so that you could download it?  I would verify that web certs work but it's okay if the PDF cert behavior is not fully correct.

**Comment by mariajgrimaldi** [comment]
Thanks for your insight! Well, [here](https://github.com/openedx/build-test-release-wg/issues/167) I described how I got to the "Download Certificate" but as you said, that button it's not working at all. Meanwhile, web certs are working just fine!

**Comment by ruzniaievdm** [comment]
@feanil Hi! During the investigate of the problem, it was decided to remove three fields `download_url`, `download_uuid`  and `key` from the model `GeneratedCertificate`
Since I am removing these fields from the model, I have a dependency to remove attributes `download_url` from `openedx-events` [repository](https://github.com/openedx/openedx-events/blob/a4c8b9409bd6667ff4682db966c7007837a7be2e/openedx_events/learning/data.py#L119) .

Should I open a PR for the openedx-events repo?

**Comment by dianakhuang** [comment]
We need to figure out if we have generated web certificates for PDF certificate holders before we can do this migration to remove the download urls. I will check in with the owning team here at edx.org.

**Comment by ruzniaievdm** [comment]
Thank I got it! Keep up to date

**Comment by pdpinch** [comment]
> it was decided to remove three fields download_url, download_uuid and key

I believe MIT uses `download_url` in the API response to build a link to user's certificates (displayed in an external portal site). (ref: https://github.com/mitodl/micromasters/blob/9f52ab55cf2381dcb6d886ddb78dca0ed9466b27/dashboard/api.py#L661-L663) 

I'm not 100% sure this is the same field however, because in the API response the value is usually a URL for the html certificate, and not a PDF certificate. I need to look into the API code a bit more.

**Comment by feanil** [comment]
@dianakhuang assigining this to you until we have an answer about the PDF certs and a migration plan for 2U.  After that we can assign to @ruzniaievdm to do the cleanup.

**Comment by dianakhuang** [comment]
The decision we made (I believe) was to leave the PDF cert fields on the models and in the API but remove the links from our frontends. If that is the case, I believe we can close this, because we have removed the UI to access these.

**Comment by feanil** [comment]
@dianakhuang should we record that as an ADR next to the model or add a relevant comment?  Seems like a forgettable decision that will cause operational pain later.

**Comment by dianakhuang** [comment]
I have written up an ADR for these decisions to leave the fields in the database and in the API: https://github.com/openedx/edx-platform/pull/31825
