### ISSUE TITLE
[DEPR]: registrar and frontend-app-program-console

### ISSUE THREAD

**Issue by kdmccormick** [openedx/public-engineering#276]
### Proposal Date

2024-08-22

Communicated: https://discuss.openedx.org/t/deprecation-removal-registrar-and-frontend-app-program-console/13730

### Target Ticket Acceptance Date

2024-09-05

### Earliest Open edX Named Release Without This Functionality

Archival on 2024-09-19

(These repos are not tagged in the Open edX release)

### Rationale

We do not believe anybody in the community other than 2U is using the [registrar](https://github.com/openedx/registrar/) micro-service nor its companion frontend [frontend-app-program-console](https://github.com/openedx/frontend-app-program-console/). This is based on informal conversations with community members as well as [a recent community outreach thread](https://discuss.openedx.org/t/site-operators-do-you-run-these-services-registrar-etc-as-part-of-your-open-edx-instance/13566). Furthermore, I have talked with @schenedx who is the 2U engineering director responsible for these repositories, and he signaled that he is supportive of deprecating them out of the Open edX project.

For context, the repositories' main features include:

* Configuring externally-managed degree programs (in Registrar's Django admin panel)
* Configuring API users who can manage those programs (in Registrar's Django admin panel)
* Bulk-enrolling students in degree programs and program-courses via an external ID, via HTTP API or CSV download/upload
  * Realizing those into actual course enrollments as soon as a user with that SSO-associated external ID exists
* Bulk-fetching grades for students in program-courses, via HTTP API or CSV download

These features, while theoretically useful to community site operators, have not been reconciled with other similar Open edX concepts like Catalog programs, the generic external_id system, CourseRoles, or PendingUserEnrollments. Instead, Registrar and Program Console exist mostly as loosely-coupled integrations with their own set of bespoke concepts. Therefore, as we believe that only 2U is using it, it would make sense for them to take over management and maintenance via their own fork.

### Removal

Both repositories will be transferred to openedx-unsupported and then archived. Site operators who use Registrar and Program Console are encouraged to fork and continue maintenance in their own GitHub organization.

#### Note on program_enrollments

Registrar and Program Console are supported by the [edx-platform program_enrollments HTTP API and models](https://github.com/openedx/edx-platform/tree/master/lms/djangoapps/program_enrollments). We are **not** deprecating and removing program_enrollments just now as part of this ticket. However, in the future, we **may** use the removal of Registrar and Program Console as justification for deprecating program_enrollments, under the understanding that non-Core edx-platform features should be implemented as plugins.

### Replacement

None

### Deprecation

None

### Migration

No plan

### Additional Info

N/A

### Task List

- [ ] Move both repositories to openedx-unsupported and archive them

**Comment by Zacharis278** [comment]
No problems with this in general. However, the discuss announcement indicates these will move to unsupported 'immediately'. I think we need to coordinate a longer timeframe for that work so 2U has the opportunity to move this onto a fork. AFAIK we'd lose the ability to maintain this if there are requirements or prod issues that need to be addressed and this in is moved to openedx-unsupported.

**Comment by kdmccormick** [comment]
@Zacharis278 Would a 1 week buffer after the DEPR is accepted work for you folks to fork and update your GH URL refs?

**Comment by Zacharis278** [comment]
candidly, we likely need more than that to be on the safe side. I know this isn't actually that much work, but we need time to plan this in and have a few high priority tasks that can't get interrupted. I'd propose we aim for 9/19 or 9/26?

**Comment by kdmccormick** [comment]
9/19 sounds good to me 👍
