### ISSUE TITLE
[DEPR]: Retire LegacyWaffle classes

### ISSUE THREAD

**Issue by feanil** [openedx/public-engineering#28]
### Proposal Date

29 April 2021

### Ticket Acceptance Date

TBD

### Technology Removal Date

TBD

### First Open edX Named Release Without This Functionality

TBD

### Rationale

This has been replaced with a new kind of waffle flag.

### Removal

* Remove all uses of LegacyWaffle* classes. 
  * See private New Relic dashboard do see usage: https://one.nr/0a2wdZ2xGjE
* Delete actual [legacy classes](https://github.com/edx/edx-toggles/blob/master/edx_toggles/toggles/internal/waffle/legacy.py).
* Remove [outdated docs](https://edx.readthedocs.io/projects/edx-toggles/en/latest/how_to/documenting_new_feature_toggles.html#refactor-legacywaffle-classes), or any other references.

### Replacement

Modern waffle flags.

### Additional Info

* Most updates should be relatively simple. [See instructions](https://edx.readthedocs.io/projects/edx-toggles/en/latest/how_to/documenting_new_feature_toggles.html#refactor-legacywaffle-classes).
* CourseWaffleFlag may require some maneuvering, like __future__.CourseWaffleFlag and rename to LegacyCourseWaffleFlag to retire.

Original Jira Issue: https://openedx.atlassian.net/browse/DEPR-153

**Comment by dyudyunov** [comment]
[ORA repo](https://github.com/openedx/edx-ora2/blob/master/openassessment/xblock/config_mixin.py) seems to be affected by removing the LegacyWaffle* code.

**Comment by feanil** [comment]
Yep, looks good to me. Closing!
