### ISSUE TITLE
[DEPR]: ConfigurationModel

### ISSUE THREAD

**Issue by feanil** [openedx/public-engineering#30]
### Proposal Date

24 February 2021

### Ticket Acceptance Date

TBD

### Technology Removal Date

TBD

### First Open edX Named Release Without This Functionality

TBD

### Rationale

The capabilities that ConfigModels provides are duplicated by Django Settings and Django Waffles, 2 upstream libraries. There is less of a need to maintain our own config management library.

### Removal

TBD - need to fill in with more info here.

We are removing ConfigurationModel, provided in https://github.com/edx/django-config-models, in favor of Django Settings and Django Waffles.

### Replacement

Django Waffles and Django Settings

### Additional Info

Original Jira Issue: https://openedx.atlassian.net/browse/DEPR-149

**Comment by robrap** [comment]
@feanil: 
* ConfigModels are used for more than toggles (booleans). Is this DEPR ticket simply stating that ConfigModels will continue to exist, but they shouldn't be used for toggles? Or, was the hope to remove them entirely? I don't think we have a replacement in all cases, and we may simply want to better document (if needed), where and when to use this and when not to.
* The toggles documentation still includes ConfigModels, and tried to note that it should be the last option, and only used in cases where it is providing a feature that is not available for any of the other methods: https://edx.readthedocs.io/projects/edx-toggles/en/latest/how_to/implement_the_right_toggle_type.html. Again, even if we never used ConfigModels for toggles, I don't think we have a good alternative for the non-toggle use cases.

Food-for-thought when determining whether to announce or close this issue. Thanks.

**Comment by robrap** [comment]
Some thoughts on the replacement plan:
* Who needs to update the config in each case? Would they only have access to Django admin, or would they be able to update settings?
* Could the size of the data ever be too bulky for settings?

**Comment by kdmccormick** [comment]
As I understand it, this deprecation was abandoned because we do not have a clear replacement for non-boolean ConfigurationModel values.

**Comment by robrap** [comment]
@kdmccormick: I'm not 100% certain about all the features of ConfigurationModel. 
- In some cases, when Django Admin is not required, are traditional Django Settings enough? I think ConfigurationModel predated edx.org's remote config, and I imagine Tutor provides quicker updates for config changes?
- For toggles where admin is required, is waffle enough?
- Would a custom Django Admin with a history table provide the same feature set for anything else? If not, what does ConfigurationModel provide?
