### ISSUE TITLE
[DEPR]: BLOCK_STRUCTURES_SETTINGS['PRUNING_ACTIVE'] in edx-platform

### ISSUE THREAD

**Issue by feanil** [openedx/public-engineering#31]
### Proposal Date

9 February 2021

### Ticket Acceptance Date

1 March 2021

### Technology Removal Date

TBD

### First Open edX Named Release Without This Functionality

TBD

### Rationale

See removal section.

### Removal

Removing: Toggle labeled 'BLOCK_STRUCTURES_SETTINGS['PRUNING_ACTIVE']. The toggle has the following annotation as a description: 

> When True, only a specified number of versions of block structure files are kept for each structure, and the rest are cleaned up. The number of versions that are kept can be specified in the BlockStructureConfiguration, which can be edited in Django Admin. The default number of versions that are kept is 5.

This setting current defaults to False, but we will be setting it as True to avoid having issues when deprecating block_structure.storage_backing_for_cache, which we will make default to True. See https://openedx.atlassian.net/browse/DEPR-145
 . Keeping this feature enabled helps prevent run away storage use.

### Replacement

No replacement is intended as no use case can be found for disabling it. It will stay enabled, keeping cached versions of block structure in storage.

### Additional Info

Original Jira Issue: https://openedx.atlassian.net/browse/DEPR-146

Original Context Conversation: https://github.com/edx/edx-platform/pull/26175/files#r565801078

**Comment by feanil** [comment]
This was announced a while back: https://discuss.openedx.org/t/deprecation-removal-several-block-structure-caching-settings-depr-143-depr-144-depr-145-depr-146/4288

We can mark it as communicated.

**Comment by dianakhuang** [comment]
We have a PR to address this, but we need to figure out what's going on with the test failures: https://github.com/openedx/edx-platform/pull/32496
