### ISSUE TITLE
[DEPR]: block_structure.invalidate_cache_on_publish in edx-platform

### ISSUE THREAD

**Issue by feanil** [openedx/public-engineering#33]
### Proposal Date

9 February 2021

### Ticket Acceptance Date

1 March 2021

### Technology Removal Date

TBD

### First Open edX Named Release Without This Functionality

TBD

### Rationale

https://github.com/edx/edx-platform/pull/26175/files#r565800087

### Removal

Removing: Toggle labeled 'block_structure.invalidate_cache_on_publish'. The toggle has the following annotation as a description: 

> When enabled, the block structure cache is invalidated when changes to courses are published. If block_structure.storage_backing_for_cache is active, all block structures related to the published course are also cleared from storage.

This toggle defaults to False and has found to be unused by edX. It was intended to be used only for a short period when it was introduced several years ago, and at this time we do not know of anyone using it.

### Replacement

There is no intended replacement for this setting, as we are not aware of a situation where it is best to enable. Per Nimisha:

> The default is to NOT invalidate the cache immediately. That is, to rely on eventual consistency. Some clients may still continue to use the old cached value, while the new cached value is being computed. This is a more robust solution for a distributed environment. I would be surprised if another Open edX instance really needed this toggle enabled.

### Additional Info

Initial Conversation: https://github.com/edx/edx-platform/pull/26175/files#r565800087
Original Jira Issue: https://openedx.atlassian.net/browse/DEPR-144

**Comment by Yagnesh1998** [comment]
https://github.com/openedx/edx-platform/pull/32407/commits/35e3dfff562b61729d023212f0365a9ddf9c3d14
