### ISSUE TITLE
[DEPR]: EdxRestApiClient

### ISSUE THREAD

**Issue by feanil** [openedx/public-engineering#37]
### Proposal Date

2 April 2019

### Ticket Acceptance Date

2 May 2019

### Technology Removal Date

30 May 2019

### First Open edX Named Release Without This Functionality

TBD

### Rationale

EdxRestApiClient is no longer supported, as you may have been able to tell from the many, many deprecation warnings. 

### In Progress or already done

- [x] #49

### Ready for Removal

Repos where we're still using EdxRestApiClient:

- [x] #48
- [x] #47
- [x] #46
- [x] #45
- [x] #44
- [x] #42
- [x] #41
- [x] #40
- [x] #39
- [x] #38
- [x] #159
- [ ] Remove the old client and publish a new breaking version of the client.

### Currently Private, can't move forward yet

- [x] #43

### Replacement

As an alternative, use OAuthAPIClient instead: https://github.com/edx/edx-rest-api-client/blob/master/edx_rest_api_client/client.py#L88

We will be switching usages of the old client to OAuthAPIClient as part of this removal.

### Additional Info

Original Jira Issue: https://openedx.atlassian.net/browse/DEPR-21

**Comment by dianakhuang** [comment]
Found a lingering instance of the EdxRestApiClient in openedx/taxonomy-connector: https://github.com/openedx/taxonomy-connector/blob/e196006978e56c75dda56553e324cfbd06da50fb/taxonomy/emsi/client.py

**Comment by feanil** [comment]
We need to do one last search to confirm that there isn't any usage of the old code and then we can remove the class from the library and release a new breaking version.

**Comment by dianakhuang** [comment]
I checked in edx.org New Relic, and there aren't any active usages on edx.org left.

**Comment by robrap** [comment]
@feanil @dianakhuang: I noticed a little remaining around this:
* See https://github.com/search?q=org%3Aopenedx%20EdxRestApiClient&type=code
* Example: https://github.com/openedx/edx-platform/blob/6cae1fa42953ff4d8ef5891b40194b104c2e477c/openedx/core/djangoapps/commerce/utils.py#L56
