### ISSUE TITLE
[DEPR]: Course Home Outline and Dates tabs -> micro-frontend

### ISSUE THREAD

**Issue by feanil** [openedx/public-engineering#50]
### Proposal Date

2 September 2020

### Ticket Acceptance Date

5 October 2020

### Technology Removal Date

 April 18, 2022

### First Open edX Named Release Without This Functionality

 O* (we will merge these changes after Nutmeg release is cut and not cherry-pick over to the release branch)

### Rationale
As part of our re-platforming effort, we are replacing Django-server-side rendered frontend implementations in favor of React-based micro-frontend implementations. This ticket covers the pages related to the Outline tab and Dates tab of Course Home.

### Removal

We are removing edx-platform's older implementation of the Django-server-side rendering of the Course Home pages.

### Replacement

We are replacing this page with the new micro-frontend-based implementation:

* ['course-home' within frontend-app-learning](https://github.com/edx/frontend-app-learning/tree/master/src/course-home)

### Additional Info

Original Jira Issue: https://openedx.atlassian.net/browse/DEPR-123

**Comment by jmyatt** [comment]
I'm not able to edit the description of this issue, but some updated information:

**Technology Removal Date**
April 18, 2022

**First Open edX Named Release Without This Functionality**
O* (we will merge these changes after Nutmeg release is cut and not cherry-pick over to the release branch)


_...also removing mention of the Progress tab from the scope of this work:_

**Rationale**
As part of our re-platforming effort, we are replacing Django-server-side rendered frontend implementations in favor of React-based micro-frontend implementations. This ticket covers the pages related to the Outline tab and Dates tab of Course Home.

**Comment by feanil** [comment]
Updated assigned for tracking purposes.

**Comment by kdmccormick** [comment]
Related removal PR: https://github.com/openedx/edx-platform/pull/30064

**Comment by mikix** [comment]
Also https://github.com/openedx/edx-platform/pull/29846 which removes the dates tab. Those two PRs (dates & outline tabs) will together remove the need for the course home legacy waffle flag. We'll still have the progress tab legacy waffle flag hanging around, since that's a bit of a slower transition. But progress is being made, pun sort of intended.

**Comment by mikix** [comment]
Oh and I plan to land both right after Nutmeg is cut. No reason to land these at the last second for Nutmeg. Might as well give folks another release with both options to ease transitions and help us find edge cases.

**Comment by kdmccormick** [comment]
Thanks for waiting for the cut @mikix . I'll try to sure the release notes are clear that Nutmeg is the last release where the Learning MFE isn't required.

**Comment by mikix** [comment]
Just a heads up that the dates and outline tab removals have landed in master (i.e. for the Olive release). Those were the two PRs linked above.

The progress tab is yet to be removed (the only "course home" tab left that has a version in both the legacy and MFE sides). Plus there are some tabs like instructor, custom course tabs, etc that aren't in the MFE at all. But that's two down!

**Comment by kdmccormick** [comment]
Is there a separate DEPR issue for the progress page?
