### ISSUE TITLE
[DEPR]: Remove VerifiedTrackCohort

### ISSUE THREAD

**Issue by feanil** [openedx/public-engineering#63]
## Replacement, Migration, and Removal

Dave proposes a process here: https://openedx.atlassian.net/wiki/spaces/AC/pages/858457019/VerifiedTrackCohortRemoval

## Target Dates

Accepted (deadline for comments before acceptance): TBD

Removed: TBD

First named release without it: TBD

### Additional Info
Original Jira Issue: https://openedx.atlassian.net/browse/DEPR-56

**Comment by feanil** [comment]
The majority of the VerifiedTrackCohort Code has been removed, we kept the partition scheme for now and @dyudyunov will investigate further.

**Comment by pdpinch** [comment]
Where can I find more information about this deprecation? After this is removed, will there still be a way to limit access to content to paid learners?

**Comment by feanil** [comment]
This deprecation removed the tooling that would automatically add cohorts based on the enrollment track. So I think it removes the ability to use cohorts to show different content to verified and unverified learners. However other forms of partitioning users still exists and can still be used to limit access to content.  eg. FBE(Content Type Gating) is still around.

**Comment by dyudyunov** [comment]
@pdpinch I've created the [discussion post](https://discuss.openedx.org/t/deprecation-removal-verifiedtrackcohort-depr-63/7334) to reflect possible problems

**Comment by dyudyunov** [comment]
@feanil please check if this issue could be closed now

**Comment by feanil** [comment]
Yep, I think this is done.  We've cleaned up as much as we can and we'll leave the rest as it is being actively used by people.
