### ISSUE TITLE
[DEPR]: Update username_replacement_service_worker to move from DOP/OIDC to DOT/JWT

### ISSUE THREAD

**Issue by feanil** [openedx/public-engineering#64]
### Additional Info
Original Jira Issue: https://openedx.atlassian.net/browse/DEPR-55

**Comment by robrap** [comment]
@feanil : What is this? Are we still using DOP somewhere? There is no information in either ticket.

**Comment by feanil** [comment]
@robrap I'm not sure about that.  I copied over the ticket just as a part of the transition and don't have any more context here.  If you think it's not relevant, we can probably close.

**Comment by robrap** [comment]
@feanil: I will move this ticket to DONE. The only references I could find to `username_replacement_service_worker` are with `USER_REPLACEMENT_USER` setting and permission classes like https://github.com/openedx/credentials/blob/34ce3d5abd4d1414bbc5f665fa4c6fccb60f480e/credentials/apps/api/v2/permissions.py#L45-L51. Monitoring shows that JWTs are used with all our retirement endpoints.
