### ISSUE TITLE
[DEPR]: ecommerce Basket Page -> micro-frontend

### ISSUE THREAD

**Issue by feanil** [openedx/public-engineering#68]
As part of our re-platforming effort, we are replacing Django-server-side rendered frontend implementations in favor of React-based micro-frontend implementations. This ticket covers the Basket Page in the ecommerce service.

### Removal

We are removing ecommerce's older implementation of the [Django-server-side rendering of the Basket Page](https://github.com/edx/ecommerce/blob/bac9455c5fe9d2b75af9ddaaf4bdae6ffd37ba15/ecommerce/extensions/basket/views.py#L120).

### Replacement

We are replacing the Basket page with a new micro-frontend-based implementation: [edx/frontend-app-payment](https://github.com/edx/frontend-app-payment)

### Target Dates

NOTE: Remember to update the annotation in the code once we are closer to the date and have a better understanding of the target dates.

* *Communication:* https://discuss.openedx.org/t/deprecation-removal-legacy-frontend-implementations-depr-17-depr-42-depr-109/3193
* *Accepted (deadline for comments before acceptance):* 2020-10-05 (World Teacher's Day)
* *Removed:* 2021-04-10
* *First named release without it:* TBD (Lilac? Maple?)

### Additional Info
Original Jira Issue: https://openedx.atlassian.net/browse/DEPR-42

**Comment by dianakhuang** [comment]
With the deprecation of ecommerce entirely, I believe we are basically not doing any work on this ticket itself: https://github.com/openedx/public-engineering/issues/22
