### ISSUE TITLE
[DEPR]: Remove getTextFromElement from paragon

### ISSUE THREAD

**Issue by feanil** [openedx/public-engineering#72]
### Removal

There's a secondary decision to deprecate a small part of paragon's utils nested within https://github.com/edx/paragon/pull/349. This will involve removing [getTextFromElement](https://github.com/edx/paragon/blob/9a025c7702c4ebd28a318b15f7aca90c556854ba/src/utils/getTextFromElement.js) from the paragon utils.

### Replacement
Uses of this utility will need to be replaced with 2 component {{props}}: one for the string version of the label and one for the html-laden component.

### Target Dates

I'll update the deprecation to communicated/the rest once I've verified there'll be no major changes to the ADR at the next fedx meeting. But as a rough estimate:

Accepted: 11/01 (one week from the FedX Meeting in which I expect the corresponding ADR to be accepted)

### Additional Info
Original Jira Issue: https://openedx.atlassian.net/browse/DEPR-5

**Comment by adamstankiewicz** [comment]
I believe we can close out this issue, as `@edx/paragon` no longer uses / implements `getTextFromElement`?
