### ISSUE TITLE
[DEPR]: registration.enable_failure_logging

### ISSUE THREAD

**Issue by Ian2012** [openedx/public-engineering#84]
### Proposal Date

10 June 2022

### Ticket Acceptance Date

27 July 2023

### Technology Removal Date

27 July 2023

### First Open edX Named Release Without This Functionality

Quince

### Rationale

It's a temporary toggle that needs to be removed from the platform. It enables the logging of validation errors in the registration process.

```
 def _log_validation_errors(self, request, errors, status_code):
        if not REGISTRATION_FAILURE_LOGGING_FLAG.is_enabled():
            return
        ...
```

After removal executed without any validation

### Removal

- The validation [here](https://github.com/openedx/edx-platform/blob/master/openedx/core/djangoapps/user_authn/views/register.py#L682-L683)

- The feature flag definition [here](https://github.com/openedx/edx-platform/blob/master/openedx/core/djangoapps/user_authn/views/register.py#L118)

- This import here and their usages [here](https://github.com/openedx/edx-platform/blob/master/openedx/core/djangoapps/user_authn/views/tests/test_register.py#L52) and [here](https://github.com/openedx/edx-platform/blob/master/openedx/core/djangoapps/user_authn/views/tests/test_register.py#L319-L355)

### Replacement

None

### Additional Info

Discussion thread: https://discuss.openedx.org/t/deprecation-removal-registration-enable-failure-logging/7463

**Comment by dianakhuang** [comment]
Whoever picks up this ticket should also be clear about what will be the behavior after the toggle is removed (picking whether it keeps all the log messages or not).

**Comment by robrap** [comment]
[inform] I confirmed that edx.org has this disabled, so I am guessing that the disabled behavior is what we want to keep.
